platform: 'cypress'
external:
    - identifier : "urn:maxbotix:mb7383"
      communication_protocol : "ttl"
      pins:
          power : '12,6'
          generic_uart_rx : '12,7'
    - identifier : "urn:maxbotix:mb7383"
      communication_protocol : "ttl"
      pins:
          power : '12,4'
          generic_uart_rx : '12,3'
      overrides :
          dynamic :
              label :
                  - "maxbotix_2_depth"
    - identifier : "urn:decagon:gs3"
      communication_protocol : "ttl"
      pins:
          power : '3,0'
          generic_uart_rx : '3,1'
    - identifier : 'urn:battery_internal'
      communication_protocol : 'analog_delsig'
      pins:
          power : '12,1'
          analog_delsig_signal : '0,0'
internal:
    - identifier : "urn:cypress:sleeptimer"
