# Component description
identifier : "urn:decagon:gs3"
manufacturer : "Decagon"
name : "GS3 Greenhouse Sensor"
description : "Ruggedized soil moisture, temperature, and electrical conductivity sensor"
alias: "gs3"

# Metadata
pinout:
    - "digital output"
    - "positive power (vcc)"
    - "ground"

# Communications
default_communication_protocol : "ttl"
supported_communication_protocols:
    ttl:
        static:
            data_bits : 8
            parity : "none"
            parity_api_control : 0
            stop_bits : 1
            flow_control : "none"
            logic_level : "high"
        dynamic:
            baud : 1200
            on_time : 800
            nvars : 4
            buffer_len : 5
            str_start :
                - "\t"
                - " "
                - " "
                - "w"
            str_end :
                - " "
                - " "
                - "\r"
                - "\r\n"
            invalid :
                - -9999
                - -9999
                - -9999
                - -9999
            regex : "\t([0-9.]+) ([0-9.]+) ([0-9.]+)\rw([0-9]+)\r\n"
            label:
                - "decagon_soil_dielec"
                - "decagon_soil_temp"
                - "decagon_soil_conduct"
                - "decagon_checksum"
        components:
            - "generic_uart_rx"
            - "power"
    sdi12:
        baud_rate : 1200
        data_bits : 7
        parity : "even"
        parity_api_control : 0
        stop_bits : 1
        logic_level : "low"
        flow_control : "none"
        parsing_logic:
            regex : "1([+-][0-9.]+)([+-][0-9.]+)([+-][0-9]+)\r\n"
            groups:
                - "dielectric"
                - "temperature"
                - "conductivity"
        components:
            - "sdi12_uart_rx"
            - "sdi12_uart_tx"
            - "power"


