generic_uart:
    dynamic_memory:
        labels:
            type: "char*" 
        readings:
            type: "float"
        invalid:
            type: "float"
        str_starts:
            type: "char*"
        str_ends:
            type: "char*"
    struct_elems:
        baud : "baud"
        on_time : "on_time"
        generic_uart_rx : "mux_term"
        power : "power_term"
        nvars : "nvars"
        readings : "readings"
        labels : "labels"
        invalid : "invalid"
        str_starts : "str_starts"
        str_ends : "str_ends"
analog_delsig:
    dynamic_memory:
        labels:
            type: "char*" 
        readings:
            type: "float"
        invalid:
            type: "float"
    struct_elems:
        on_time : "on_time"
        generic_uart_rx : "mux_term"
        power : "power_term"
        analog_convert_volts : "analog_convert_volts"
        analog_gain_numerator : "analog_gain_numerator"
        analog_gain_denominator : "analog_gain_denominator"
        nvars : "nvars"
        readings : "readings"
        labels : "labels"
        invalid : "invalid"
analog_sar:
    dynamic_memory:
        labels:
            type: "char*" 
        readings:
            type: "float"
        invalid:
            type: "float"
    struct_elems:
        on_time : "on_time"
        generic_uart_rx : "mux_term"
        power : "power_term"
        analog_convert_volts : "analog_convert_volts"
        analog_gain_numerator : "analog_gain_numerator"
        analog_gain_denominator : "analog_gain_denominator"
        nvars : "nvars"
        readings : "readings"
        labels : "labels"
        invalid : "invalid"

