generic_uart:
    dynamic_memory:
        label:
            type: "char*" 
        reading:
            type: "float"
        invalid:
            type: "float"
        str_start:
            type: "char*"
        str_end:
            type: "char*"
    struct_elems:
        baud : "baud"
        on_time : "on_time"
        generic_uart_rx : "mux_term"
        power : "power_term"
        nvars : "nvars"
        reading : "readings"
        label : "labels"
        invalid : "invalid"
        str_start : "str_starts"
        str_end : "str_ends"
analog_delsig:
    dynamic_memory:
        label:
            type: "char*" 
        reading:
            type: "float"
        invalid:
            type: "float"
    struct_elems:
        on_time : "on_time"
        analog_delsig_signal : "mux_term"
        power : "power_term"
        analog_convert_volts : "analog_convert_volts"
        analog_gain_numerator : "analog_gain_numerator"
        analog_gain_denominator : "analog_gain_denominator"
        nvars : "nvars"
        reading : "readings"
        label : "labels"
        invalid : "invalid"
analog_sar:
    dynamic_memory:
        label:
            type: "char*" 
        reading:
            type: "float"
        invalid:
            type: "float"
    struct_elems:
        on_time : "on_time"
        analog_sar_signal : "mux_term"
        power : "power_term"
        analog_convert_volts : "analog_convert_volts"
        analog_gain_numerator : "analog_gain_numerator"
        analog_gain_denominator : "analog_gain_denominator"
        nvars : "nvars"
        reading : "readings"
        label : "labels"
        invalid : "invalid"

