generic_uart:
    base:
        - "generic_uart"
        - "generic_uart_mux"
        - "generic_uart_mux_controller"
        - "generic_uart_rx_isr"
        - "generic_uart_reset"
        - "generic_uart_clock"
    peripheral:
        - "generic_uart_rx_0"
        - "generic_uart_rx_1"
        - "generic_uart_rx_2"
        - "generic_uart_rx_3"
rs485_uart:
    base:
        - "rs485_uart"
        - "rs485_comparator"
        - "rs485_pos"
        - "rs485_neg"
        - "rs485_clock"
        - "rs485_reset"
        - "rs485_rx_isr"
i2c:
    base:
        - "i2c"
        - "i2c_sda"
        - "i2c_scl"
        - "i2c_clock"
analog_delsig:
    base:
        - "analog_delsig_adc"
        - "analog_delsig_mux"
    peripheral:
        - "analog_delsig_signal_0"
        - "analog_delsig_signal_1"
analog_sar:
    base:
        - "analog_sar_adc"
        - "analog_sar_mux"
    peripheral:
        - "analog_sar_signal_0"
        - "analog_sar_signal_1"
power:
    base:
        - "power_signal"
        - "power_demux"
        - "power_demux_controller"
    peripheral:
        - "power_0"
        - "power_1"
        - "power_2"
        - "power_3"
        - "power_4"
        - "power_5"
        - "power_6"
        - "power_7"

