protocols:
    ttl :    "generic_uart"
    rs232 :  "generic_uart"
    rs485 :  "rs485_uart"
    sdi12 :  "sdi12_uart"
    i2c :    "i2c"
    analog_delsig : "analog_delsig"
    analog_sar : "analog_sar"
parameters:
    uart:
        baud_rate:
            alias : "BaudRate"
            mappings : ~
        flow_control:
            alias : "FlowControl"
            mappings: 
                "none" : "B_UART__FCNone"
                "hardware" : "B_UART__FCHardware"
        data_bits:
            alias : "NumDataBits"
            mappings:
                5 : "B_UART__DB5"
                6 : "B_UART__DB6"
                7 : "B_UART__DB7"
                8 : "B_UART__DB8"
                9 : "B_UART__DB9"
        stop_bits:
            alias : "NumStopBits"
            mappings:
                1 : "B_UART__SB1"
                2 : "B_UART__SB2"
        parity:
            alias : "ParityType"
            mappings:
                "none" : "B_UART__None_revB"
                "even" : "B_UART__Even_revB"
                "odd"  : "B_UART__Odd_revB"
                "mark/space"  : "B_UART__Mark_Space_revB"
